name: bsky

services:
  broadcaster:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_broadcaster.py

  filter:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - broadcaster
    environment:
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_filter.py

  indexer:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - broadcaster
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_indexer.py

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        mode: 0444 # Optional: Set read-only permissions
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"  # Allow anonymous access for simplicity (not recommended for production)
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

volumes:
  prometheus-data:
  grafana-data:


configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'firehose_filter'
          static_configs:
            - targets: ['filter:6000']

        - job_name: 'firehose_indexer'
          static_configs:
            - targets: ['indexer:6000']
