name: bsky

services:
  broadcaster:
    build: ./backend
    volumes:
      - ./backend:/app:cached
    environment:
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_broadcaster.py

  filter:
    build: ./backend
    volumes:
      - ./backend:/app:cached
    depends_on:
      - broadcaster
    environment:
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_filter.py

  indexer:
    build: ./backend
    volumes:
      - ./backend:/app:cached
    depends_on:
      - broadcaster
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FIREHOSE_MAXLEN=${FIREHOSE_MAXLEN}
      - REDIS_URI=${REDIS_URI}
    command: python firehose_indexer.py

  prometheus:
    image: prom/prometheus:latest
    user: "1000"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"  # Allow anonymous access for simplicity (not recommended for production)
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

volumes:
  prometheus-data:
  grafana-data:
