name: bsky

services:
  nats:
    image: nats:2-alpine
    ports:
      - "8222:8222"
      - "4222:4222"
    volumes:
      - nats-data:/data
    command: "-js -sd /data --http_port 8222"

  exporter:
    image: natsio/prometheus-nats-exporter
    restart: always
    command: "-channelz -connz_detailed -healthz -gatewayz -accstatz -leafz -jsz all -routez -serverz -subz -varz http://nats:8222/"
    depends_on:
      - nats
    
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  prometheus-data:
  nats-data:

configs:
  prometheus_config:
    file: ./prometheus.yml