name: bsky

services:
  redis:
    image: redislabs/redismod
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ${REDIS_DATA_FOLDER}:/data
    command: "--loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redistimeseries.so --save 60 1"
  
  redis_insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redis-insight:/db
    depends_on:
      - redis
      
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  redis-insight:
  mongodb-data: