name: bsky

services:
  nats:
    image: nats:2-alpine
    ports:
      - '4222:4222'
    restart: always
    volumes:
      - nats-data:/data
    command: "-js -sd /data --http_port 8222"

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - '9042:9042'
    volumes:
      - cassandra-data:/var/lib/cassandra

  nats_exporter:
    image: natsio/prometheus-nats-exporter
    restart: always
    ports:
      - '7777:7777'
    command: "-channelz -connz_detailed -healthz -gatewayz -accstatz -leafz -jsz all -routez -serverz -subz -varz http://nats:8222/"
    depends_on:
      - nats

volumes:
  nats-data:
  cassandra-data:

