name: bsky

services:
  nats:
    image: nats:2-alpine
    ports:
      - '4222:4222'
    restart: always
    volumes:
      - ${NATS_DATA_FOLDER}:/data
    command: "-js -sd /data --http_port 8222"

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ${MONGO_DATA_FOLDER}:/data/db

  nats_exporter:
    image: natsio/prometheus-nats-exporter
    restart: always
    ports:
      - '7777:7777'
    command: "-channelz -connz_detailed -healthz -gatewayz -accstatz -leafz -jsz all -routez -serverz -subz -varz http://nats:8222/"
    depends_on:
      - nats

  mongodb_exporter:
    image: percona/mongodb_exporter:0.43.1
    restart: always
    ports:
      - '9216:9216'
    command:
      - --mongodb.uri=mongodb://mongo:27017/
      - --collect-all
    depends_on:
      - mongo
