global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'firehose_filter'
    static_configs:
      - targets: ['filter:6000']

  - job_name: 'firehose_indexer'
    static_configs:
      - targets: ['indexer:6000']
