name: Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # or the tag of your runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          # Example using SSH and an environment variable 
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_IP }} << EOF
            cd /opt/bsky-codes/
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF